### PR TITLE
added a chrome extension

### PR DESCRIPTION
**Pull request by VedantPol**
created a manifest.json file required for Chrome-extension

### CODE REVIEW

**Comment by ankushKun** [comment]
Hi @VedantPol, sorry but I don't think just adding a manifest.json is enough to make a chrome extension.
Do you plan to make more changes?

**Comment by VedantPol** [comment]
hey @ankushKun , The manifest.json file works fine for the first iteration.  Are you having difficulties adding the extension? just go to the manage extension setting on chrome and select the "load unpacked" option then select the  'animedoro-timer/Animedoro' file. Since the project is made in vanilla CSS and HTML not much is required to create an extension of the following project. You just need a good manifest.json file. 
 I do plan on more features like adding a logo, adjusting the size accordingly, and adding more effective buttons. But for the first iteration, it looks fine to me :)
chrome-extenshion-2

**Comment by ankushKun** [comment]
Oh that's cool!
It would be great if you could also add the packaged file for easier installation.

Thank you for your contributions! 
Happy Hacking

**Comment by VedantPol** [comment]
sure will add the packaged files too :)

**Comment by VedantPol** [comment]
Created an icon folder in images that contains logos of 3 sizes (16x16, 48x48, and 128x128 )
The following sizes were recommended for the chrome extension (https://developer.chrome.com/docs/extensions/mv2/manifest/icons/). Also packed the extension with **Animedoro.crx** being the packed file and **Animedoro.pem
** being the primary key for it. When updating the extension use the Animedoro.pem key or delete the key and generate a new one :)

**Comment by ankushKun** [comment]
merged 👍

**Pull request merged**
